<?php

namespace WCS\ShareKanBundle\Repository;

/**
 * playlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class playlistRepository extends \Doctrine\ORM\EntityRepository
{
}
